const paragraphs = [
    "As I sit in my room late at night, staring at the computer screen, I decide it would be a good idea to create this text. There isn't much meaning to it, other than to get some simple practice. A lot of the texts that have been created are rather short, and don't give a good representation of actual typing speed and accuracy. They lack the length to gauge where your strengths and weaknesses are when typing.",
    "global energy sources become more and more stressed, solar power is called new energy development, and we use more solar cells in our lives. The solar cell is based on semiconductor materials. The absorption of light-electric material is followed by light energy and photo-electrical conversion, so that it generates current, what is the working principle of solar cell? A solar cell is a device that directly converts light energy into electrical energy through a photo-electric effect or a photo-electric effect. When the sun shines on a semiconductor, some of it is reflected off the surface and the rest is absorbed or transmitted by the semiconductor.",
    "My grandmother, like everybody's grandmother was an old woman, she had been old and wrinkled for the twenty years that I had known her. People said that she had once been young and pretty and even had a husband. But that was hard to believe. My grandfather's portrait hung above the mantelpiece in the drawing-room.",
    "He wore big turban and loose-fitting clothes. His long, white beard covered the best part of his chest and he looked at least a hundred years. His long, white beard covered the best part of his chest and he looked at least a hundred years old. He did not look the sort of person who would have a wife or children. He looked as if could only l have lots and lots of grandchildren. As for my grandmother being young and pretty, the thought was almost revolting. She often told us of the games she used to play as a child. That seemed quite absurd and undignified on her part and we treated it like the fables of the Prophets she used to tell us. She had always been short and fat slightly bent. Her face was a crisscross of wrinkles running from everywhere to everywhere. No, we were certain she had always been as we had known her. Old, so terribly old that she could not have grown older and had stayed at the same age for twenty years. "  ,
    "As you all know the reason behind calling each one of you and organizing this speech ceremony. The occasion is special as the position of Vice Chairman of our company which was lying vacant from so long has been filled. The position of vice president is really important as the person being given the role has to proactively participate in the policy building and both internal as well external affairs of the company. And I am glad that the relentless efforts of our HR Department to find a suitable candidate for the position have finally yielded favorable results. Having finished his graduation in Economics from D School of Economics he went on to pursue his",
    "One Monday afternoon, Mike, adopting a very unusual style, wore a hoody. Nobody would ever think of wearing a hoody on a very hot day. His friends also wondered why he was being weird. They became a little aloof with Mike that day. The next day, Mike wore a hoody again, this time of a different color. This went on every day for a week and his friends gradually got used to it. Finally, on the eighth day, Mike wore a plain white shirt, acting like nothing had been amiss for the past week. One of his friends asked him, “Are you finally done with your hoody fashion?” “What hoody fashion?” Mike asked. “Last week, everyday, you kept on wearing a hoody.” And then Mike said, “What? I was",
    "As you all know the reason behind calling each one of you and organizing this speech ceremony. The occasion is special as the position of Vice Chairman of our company which was lying vacant from so long has been filled. The position of vice president is really important as the person being given the role has to proactively participate in the policy building and both internal as well external affairs of the company. And I am glad that the relentless efforts of our HR Department to find a suitable candidate for the position have finally yielded favorable results.Having finished his graduation in Economics from D School of Economics he went on to pursue his",
    "The Contractor shall use every reasonable means to prevent any of the roads or bridges communicating with or on the routes to the Site from being damaged or injured by any traffic of the Contractor or any of his Subcontractors and, in particular, shall select routes, choose and use vehicles and restrict and distribute loads so that any such extraordinary traffic as will inevitably arise from the moving of materials, Plant, Contractor's Equipment or Temporary Works from and to the",
    "As you all know the reason behind calling each one of you and organizing this speech ceremony. The occasion is special as the position of Vice Chairman of our company which was lying vacant from so long has been filled. The position of vice president is really important as the person being given the role has to proactively participate in the policy building and both internal as well external affairs of the company. And I am glad that the relentless efforts of our HR Department to find a suitable candidate for the position have finally yielded favorable results.Having finished his graduation in Economics from D School of Economics he went on to pursue his"
    
];